sudo: required 
language: node_js
node_js:
    - "stable"
    
services: 
    - docker
before_install: 
    - docker build -t eva/sample-app -f Dockerfile.dev .
script:     
    - docker run -e CI=true eva/sample-app npm run test -- --coverage --watchAll=false
